alias ls="ls -G"
alias ..="cd .."
alias ltr="ls -ltr"
alias ll="ls -l"
alias jsonlint="python -m json.tool"
alias t="tmux attach || tmux"
alias e="fzf --preview 'bat --theme Dracula --color=always {}' | xargs -n1 -o $EDITOR"
